sentence = input("Enter your sentence: ")
print(sentence)
print('Your Sentence is: '+sentence)
word1 = input('Enter word to replace: ')
word2 = input('Enter the word to replace it with: ')
print(sentence.replace(word1, word2))
